### ISSUE TITLE
[Metrics] Add label method

### ISSUE THREAD

**Issue by SpontaneousOverthrow** [emeraldpay/dshackle#100]
It will be great to add method type(eth_call for example) for:
dshackle_request_jsonrpc_request_err_total
dshackle_request_jsonrpc_call_seconds_count
dshackle_request_jsonrpc_call_seconds_sum
dshackle_request_jsonrpc_request_total

**Comment by SpontaneousOverthrow** [comment]
this is a bit harder. Need to dynamically create metrics.
https://dzone.com/articles/spring-boot-metrics-with-dynamic-tag-values

**Comment by splix** [comment]
I see you've some code related to this feature. If you like you can make a PR so I can check it and fix if something is still not working. Also I'd like to make it configurable/optional, i.e. enabled it with extended metrics. What do you think?

**Comment by SpontaneousOverthrow** [comment]
i tried to add this feature but i didn't work, will continue today and create PR
