### ISSUE TITLE
Fallback upstreams

### ISSUE THREAD

**Issue by splix** [emeraldpay/dshackle#15]
Special role for upstream that should be used only as a fallback (and to verify head consistency).

```
- id: local
  chain: ethereum
  connection: ...
- id: infura
  role: fallback
  chain: ethereum
  connection: ...
```

**Comment by splix** [comment]
rel #7

**Comment by MysticRyuujin** [comment]
Do you have any plans to implement this any time soon?

**Comment by splix** [comment]
I think I can try to add it by v0.8, the current design should allows it

**Comment by MysticRyuujin** [comment]
Perhaps a separate feature, but related might be weight or preference values for nodes?

For instance, if I have a dshackle server hosted in New York, with nodes/targets in New York and Germany...it makes more sense for the New York server to forward requests to New York first/more often, and visa-versa for the dshackle server hosted in Germany.

Not sure if it's feasible but just a thought I had.

I wouldn't want to mark it a "backup" per-say, as I really do need a 'talk to this node only if all other options are unavailable' option. If it's hard to implement something like that though, that's totally cool, just thought I'd mention it.

**Comment by splix** [comment]
Yeah, separate feature. I was thinking about it, but not ready to implement it right now.

If you have a "weight" per node, then it may be a suboptimal route because you don't want to route this particular request to Germany if NY is, in fact, doing fine and can currently serve it. Or instead, you man have other roles, like `front` and `back,` and the Dshackle should always start with `front.` In this case, the NY node could always be overutilized, and Germany always be underutilized. It may work with rate-limiting #13, though. Will see.
