### ISSUE TITLE
FR: Add a Dockerfile 

### ISSUE THREAD

**Issue by barnabasbusa** [emeraldpay/dshackle#277]
Could you guys please add a Dockerfile which would eliminate the need to install gradle, and java. 

Also it would help us create a local docker image without needing to ensure we correctly run the build process.

**Comment by splix** [comment]
I'm not sure it's possible to make it working without Java. But you could run `./gradlew jibDockerBuild`, or just `./gradlew`, and the command would install the Gradle itself.

**Comment by barnabasbusa** [comment]
This should do it: https://github.com/emeraldpay/dshackle/pull/279
