### ISSUE TITLE
Provide error message and code from upstream

### ISSUE THREAD

**Issue by splix** [emeraldpay/dshackle#42]
Right now if an upstream responds with error, the server just gives error -32002. It makes sense to give actual code, and error message when available

**Comment by MysticRyuujin** [comment]
I'm guessing this is the issue to track the fact that we don't get the real error message from the upstream :)

**Comment by MysticRyuujin** [comment]
I'm guessing this is the issue to track the fact that we don't get the real error message from the upstream :)

**Comment by MysticRyuujin** [comment]
We had another issue asks us about this.

Real:
```
curl -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id": 18,"method": "eth_call","params": [{"data": "0x77c7b8fc","to": "0x8ee2a5aca4f88cb8c757b8593d0734855dcc0eba"},"0xa1f0fd"]}' <nethermind>
{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"revert: SafeMath: division by zero"},"id":18}
```

Dshackle:
```
curl -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id": 18,"method": "eth_call","params": [{"data": "0x77c7b8fc","to": "0x8ee2a5aca4f88cb8c757b8593d0734855dcc0eba"},"0xa1f0fd"]}' <dshackle>
{"jsonrpc":"2.0","id":18,"error":{"code":-32002,"message":"Upstream error"}}
```

**Comment by splix** [comment]
@MysticRyuujin please try v0.8.1 with the fix, just uploaded to Docker. Thank you

**Comment by MysticRyuujin** [comment]
Looks good, I gave it a try using the above curl example and it returned just fine:
```
{"jsonrpc":"2.0","id":18,"error":{"code":-32015,"message":"VM execution error.","data":"revert: SafeMath: division by zero"}}
```
