### ISSUE TITLE
Filter Requests

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#61]
I'm wondering how dshackle handles requests for eth filter methods.

I'm not an expert here but my basic understanding of how this works is:

User creates a filter with `eth_newFilter` or `eth_newPendingTransactionFilter` etc. and the return value is an index. The user then calls `eth_getFilterLogs` or something similar and provides the index number.

It is my understanding that this filter index is unique to the ETH1 node.

How does dshackle handle this? Does dshackle track those indexes internally? I don't think it does... Does dshackle sticky the filter requests? I don't know / I don't think it does...?

I've currently stapled the `filter` commands to a single node using the `enabled` methods in the config, but if that nodes goes down we loose the ability to run any filter commands.

**Comment by splix** [comment]
Yeah, that's one of the problems. Filters are supposed to be sticky per node, and it's hard to balance them. Dshackle doesn't try to do it right now, so I recommend to use labels (that would be supported only by grpc clients) or enable only on one node (as you did).

Some internal tracking needs to be implemented. But it would be hard to make it fault tolerant and with correct recoveries.

**Comment by MysticRyuujin** [comment]
If I have a fallback node, that allows the filters, would dshackle send the filter commands to the fallback node if no other nodes have that method enabled?

That might be a quick hack

**Comment by splix** [comment]
It should. Though the filter state will be unavailable on the new node, so the client must restart the filter, I guess

**Comment by MysticRyuujin** [comment]
I had an idea how you might implement this...

When someone calls for a filter to be created, you could track which node the original request went to, and return to the user a unique filter ID. You'd just need to hold a unique filter ID to node and node filter ID mapping.

This would ensure that the the same node is used for each filter the user requests, but would still allow load balancing of requests involving filters.

**Comment by easeev** [comment]
Any progress with support for sticky sessions?

**Comment by splix** [comment]
`eth_getFilterLogs` are available with WS connection, you can try with one of the latest release which supports them. 

But for sticky session though a plain HTTP request with JSON RPC it's not going to work, because Dshackle is supposed to be stateless.

I suggest to use WebSocket to connect to Dshackle, and those methods should work then.
