### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#65]
Any chance we can get a release soon? The chainID issue is causing our users some grief with metamask.

Not sure how 0.9 is coming but maybe an interim release?

**Comment by splix** [comment]
Hi @MysticRyuujin Thank you for reminding, you're absolutely right, it's time to make a release. Was just too busy with other projects. I've been using latest dev version for a while without serious issues, so I guess I'll need to fix couple of issues you faced, and it's good to go. Will do that in the following days.

**Comment by MysticRyuujin** [comment]
The v1.0.0 eth2 clients are out, but they require the chainId fix :wink:

**Comment by splix** [comment]
Finally made it :) 

https://github.com/emeraldpay/dshackle/releases/tag/v0.9.0
