### ISSUE TITLE
Java Memory vs Redis

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#80]
Background:

When running dshackle via docker, the only java memory argument given is `-Xms1024m` which is 1GB of RAM.

Our system has about 6GB of RAM available but is only consuming about 2GB or RAM under normal operations. This leaves us with about 4GB of free RAM.

Question:

What do you think would result in better performance for dshackle? Increasing the java memory limit to 3GB, or using a redis cache and just limit the redis cache to ~2GB?

Thanks!

**Comment by splix** [comment]
Dshackle is mostly stateless, and a memory required for a connection should _not_ be high. Maybe around ten kilobytes at most, but I didn't really measure yet. For some of the calls, like subscribing to an address balance change, it's slightly higher, but It's available through additional gRPC methods, but I guess you don't use them anyway. 

There is also memory to keep _short living copy_ of the call-response. And a cache for the last blocks, it's also a few megabytes, should be less than 50mb per chain. 

Keep also in mind that `-Xms1024m` is for Java heap, but JVM is also using additional memory for IO, which _by default_ is another 64mb.

Anyway, I think 1gb should be enough for your setup. If you have thousands of _simultaneous_ connections, then you can increase it and see if it improves anything. 

Redis is used to keep state, and it can be shared between Dshackle instances, so I suggest increasing its memory limit, it's more likely to improve performance.

PS working on metrics, i.e. Prometheus, etc. So it will be more visible with the next version what are actual number, and if there is any bottlenecks and so on.

**Comment by MysticRyuujin** [comment]
Thanks, that's pretty much all I wanted to know :)
